<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Project Upload</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="../css/signin.css" rel="stylesheet">
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
	<script src="../js/ie10-viewport-bug-workaround.js"></script>
	<script src="../bower_components/jquery/dist/jquery.js"></script>
	<script src="../js/main.js"></script>
</head>

<body>
	 <nav class="navbar navbar-default navbar-fixed-top">
 				<div class="col-md-5 col-md-offset-5">					
 					
 					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 						<ul class="nav navbar-nav navbar-right">
 							<li class="hidden">
 								<a href="#page-top"></a>
 							</li>
							<li class="page-scroll">
 								<a href="../profile.php/logout">Log Out</a>
 							</li>
 																													
 						</ul>
 					</div>
 					
 				</div>
    </nav>
	<br>
	<br>
	<div class="container">
		
		<div class="container">
			<div class="fb-profile">
				<img align="left" class="fb-image-lg" src="http://northbaynow.ca/wp-content/uploads/2016/05/tech.jpg" alt="Profile image example"/>
				<img align="left" class="fb-image-profile thumbnail" src="../src/propics/blank.jpg" alt="Profile image example" height="180" width="180"/>
				<div class="fb-profile-text">
					
				</div>
			</div>
		</div> 
		<div>
			<br>
		</div>
    <ul class="nav nav-pills" role="tablist">
		<?php
        	echo '<li role="presentation"><a href="../profile.php/home">Home</a></li>';
		
			if($_SESSION['userData']['approval'] == 'Yes'){
				echo '<li role="presentation" class="active"><a href="../profile.php/addproj">Add your own Project</a></li>';
			}
		
            if($_SESSION['userData']['accounttype'] == 'Admin'){
                echo '<li role="presentation"><a href="../profile.php/pending">Pending Accounts<span class="badge">';
                
                $count = 0;
                $count = countPending();
                echo $count;
                echo '</span></a></li>';
            }
        
        	echo '<li role="presentation"><a href="../profile.php/change">Update your Info</a></li>';
		
			if($_SESSION['userData']['approval'] == 'Yes'){

				echo '<li role="presentation"><a href="../profile.php/download">View and Download Projects</a></li>';
			}

		
        	echo '<li role="presentation"><a href="../profile.php/compare">Compare Code</a></li>';
		?>
    </ul>

	<br>
	<br>
	<div class="container">
	
			<form class="form-horizontal" method="POST" action="../profile.php/addAction" enctype="multipart/form-data">
				<fieldset>	
					<!-- Text input-->
					<div class="form-group">
						<label class="col-md-4 control-label" for="name">Project Name</label>
						<div class="col-md-4">
							<input id="name" name="name" type="text" placeholder="Name" class="form-control input-md" required="">
						
						</div>
					</div>

					<div class="form-group">
						<label class="col-md-4 control-label" for="name">Course Code</label>
						<div class="col-md-4">
							<input id="ccode" name="ccode" type="text" placeholder="Course Code" class="form-control input-md" required="">
						
						</div>
					</div>
					
					
					<div class="form-group">
						<label class="col-md-4 control-label" for="price">Course Name</label>
						<div class="col-md-4">
							<input id="cname" name="cname" type="text" placeholder="Course Name" class="form-control input-md" required="">
						
						</div>
					</div>

					<div class="form-group">
						<label class="col-md-4 control-label" for="price">Git Hub link</label>
						<div class="col-md-4">
							<input id="ghlink" name="ghlink" type="text" placeholder="Git link" class="form-control input-md" required="">
						
						</div>
					</div>

					<div class="form-group">
						<label class="col-md-4 control-label" for="price">Year</label>
						<div class="col-md-4">
							<input id="year" name="year" type="text" placeholder="Year" class="form-control input-md" required="">
						
						</div>
					</div>

					<div class="form-group">
						<label class="col-md-4 control-label" for="price">Upload Your Project file</label>
						<div class="col-md-4">
							<input id="upload" name="upload" type="file" accept=".zip"  class="form-control input-md" required=""> 
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-md-4 control-label" for="saveBnt"></label>
						<div class="col-md-4">
							<button id="saveBnt" name="saveBnt" class="btn btn-primary">Save Project</button>
						</div>
					</div>
				
				</fieldset>
			</form>

	

</body>
</html>
