<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang='en'>
<head>
<meta http-equiv="Content-Type" content="text/xhtml; charset=utf-8" />
<title>Compare</title>
<meta name="description" content="Online Code Difference Comparison Tool allows you to paste two pieces of code or text and view the changes between the two." />

	<script type="text/javascript" src="../js/dojo.js"></script>
	<script type="text/javascript" src="../js/diffview.js"></script>
	<link rel="stylesheet" type="text/css" href="../css/diffview.css"/>
	<script type="text/javascript" src="../js/difflib.js"></script>

	<link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="../js/result.js"></script>
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

</head>
<body>
	
	<nav class="navbar navbar-default navbar-fixed-top">
 				<div class="col-md-5 col-md-offset-5">					
 					
 					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 						<ul class="nav navbar-nav navbar-right">
 							<li class="hidden">
 								<a href="#page-top"></a>
 							</li>
							 <li class="page-scroll">
 								<a href="../profile.php/logout">Log Out</a>
 							</li>
 																											
 						</ul>
 					</div>
 					
 				</div>
    </nav>
	<br>
	<br>
	<br>
	<br>
	<div class="container">
		
		<div class="container">
			<div class="fb-profile">
				<img align="left" class="fb-image-lg" src="http://northbaynow.ca/wp-content/uploads/2016/05/tech.jpg" alt="Profile image example"/>
				<img align="left" class="fb-image-profile thumbnail" src="../src/propics/blank.jpg" alt="Profile image example" height="180" width="180"/>
				<div class="fb-profile-text">
					
				</div>
			</div>
		</div> 
		<div>
			<br>
		</div>
    <ul class="nav nav-pills" role="tablist">
        <?php
        	echo '<li role="presentation"><a href="../profile.php/home">Home</a></li>';
		
			if($_SESSION['userData']['approval'] == 'Yes'){
				echo '<li role="presentation"><a href="../profile.php/addproj">Add your own Project</a></li>';
			}
		
            if($_SESSION['userData']['accounttype'] == 'Admin'){
                echo '<li role="presentation"><a href="../profile.php/pending">Pending Accounts<span class="badge">';
                
                $count = 0;
                $count = countPending();
                echo $count;
                echo '</span></a></li>';
            }
        
        	echo '<li role="presentation"><a href="../profile.php/change">Update your Info</a></li>';
		
			if($_SESSION['userData']['approval'] == 'Yes'){

				echo '<li role="presentation"><a href="../profile.php/download">View and Download Projects</a></li>';
			}

		
        	echo '<li role="presentation" class="active"><a href="../profile.php/compare">Compare Code</a></li>';
		?>
    </ul>
	<h1>Enter your code in the text boxes below to compare</h1>

	<input type="hidden" id="contextSize" value=""></input><br/>
	<!--<input type="radio" name="_viewtype" id="sidebyside"/> Side by Side
	&#160;&#160;-->
	<input type="hidden" name="_viewtype" checked="checked" id="inline"/>
	&#160;&#160;
	<h2>First Text</h2>
	<textarea id="baseText" style="width:600px;height:300px"></textarea>

	<h2>Second Text</h2>
	<textarea id="newText" style="width:600px;height:300px"></textarea><br/>
	<input type="button" value="Submit" onclick="javascript:diffUsingJS();"/><br/><br/>
	<a name="diff"> </a>
	<div id="diffoutput" style="width:100%"> </div>
    
</div> <!-- /container -->
</body>
</html>