
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="">
	<meta name="author" content="">
	
	<title>Student Project Tracker</title>
	
	<!-- Bootstrap core CSS -->
	<link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
	<link href="css/ie10-viewport-bug-workaround.css" rel="stylesheet">
	
	<!-- Custom styles for this template -->
	<link href="css/jumbotron-narrow.css" rel="stylesheet">
	<link href="css/signin.css" rel="stylesheet">
	<script src="js/main.js"></script>


</head>

<body>
		<nav class="navbar navbar-default navbar-fixed-top">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header page-scroll">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="#page-top">Start Bootstrap</a>
					</div>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav navbar-right">
							<li class="hidden">
								<a href="#page-top"></a>
							</li>
							
							<li class="page-scroll">
								<a href="templates/stuProfile.phtml">Profile</a>
							</li>
							<li class="page-scroll">
								<a href="templates/signin.phtml">Sign In</a>
							</li>
							<li class="page-scroll">
								<a href="signup.php">Sign Up</a>
							</li>
							<li class="page-scroll">
								<a href="#portfolio">Portfolio</a>
							</li>
							<li class="page-scroll">
								<a href="#about">About</a>
							</li>
							<li class="page-scroll">
								<a href="#contact">Contact</a>
							</li>
							<!-- <nav>
									<ul class="nav nav-pills pull-right">
										<li role="presentation" class="active"><a href="index.php">Home</a></li>
										<li role="presentation" class="active"><a href="templates/stuProfile.phtml">Profile</a></li>
										<li role="presentation" class="active"><a href="templates/signin.phtml">Sign In</a></li>
										<li role="presentation" class="active" action=""><a href="signup.php">Sign Up</a></li>
									</ul>
								</nav> -->
						</ul>
					</div>
					<!-- /.navbar-collapse -->
				</div>
				<!-- /.container-fluid -->
			</nav>
			<header id="page-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<img class="img-responsive" src="http://ironsummitmedia.github.io/startbootstrap-freelancer/img/profile.png" alt="">
							<div class="intro-text">
								<span class="name">Welcome to Student Project Tracker</span>
								<hr class="star-light">
								<p class="skills">Landing Page Layout</p>
								<p class="skills">Scroll to see the effect</p>
							</div>
						</div>
					</div>
				</div>
			</header>
			<div class="content-wrapper">
				<section class="primary" id="portfolio">
					<div class="container">
						<div class="row">
							<div class="col-lg-12 text-center">
								<h2>Types of Projects</h2>
								<hr class="star-primary">
							</div>
						</div>
						<div class="row">
							<div class="col-sm-4">
								<img src="https://inhsshs.files.wordpress.com/2016/08/stem-logo-final.png?w=1024&h=400&crop=1" width="500" height="300">    
							</div>
							<br>
							<br>
							<div class="col-sm-4">
								<img src="http://www.interactarts.com/wp-content/uploads/2013/09/InteractArts_Logo_cropped.png" width="500" height="300">    
							</div>
							<br>
							<br>
							<div class="col-sm-4">
								<img src="http://schoolweb.tdsb.on.ca/portals/yorkmillsci/images/Social%20Sciences/Social_Sciences_and_Humanities_wordle.png" width="500" height="300">    
							</div>
						</div>
					</div>
				</section>
				<section class="success" id="about">
					<div class="container">
						<div class="row">
							<div class="col-lg-12 text-center">
								<h2>About</h2>
									<hr class="star-light">
							</div>
						</div>
						<div class="row">
							<div class="col-lg-4 col-lg-offset-2">
								<p>Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>
							</div>
							<div class="col-lg-4">
								<p>Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!</p>
							</div>
						</div>
					</div>
				</section>
				<section class="primary" id="contact">
					<div class="container">
						<div class="row">
							<div class="col-lg-12 text-center">
								<h2>Contact</h2>
								<table class="table table-bordered">
											<thead>
												<tr>
													<th>Project ID</th>
													<th>Project Name</th>
													<th>Course Code</th>
													<th>Course Name</th>
													<th>GitHub Link</th>
													<th>Year</th>
													<th>File</th>
													<th>Group Members</th>
												</tr>
											</thead>
											<tbody>
										<?php
											
											$conn = getDBConnection();
											$sql = "SELECT * FROM `project`";
											$res = $conn->query($sql);
											if ($res){
												$row = $res->fetch_assoc();
												while ($row != null){
													// print the rows of the table
													echo "<tr>";
													echo "<td>" . $row['id'] . "</td>";
													echo "<td>" . $row['projname'] . "</td>";
													echo "<td>" . $row['coursecode'] . "</td>";
													echo "<td>" . $row['coursename'] . "</td>";
													echo "<td>" . $row['githublink'] . "</td>";
													echo "<td>" . $row['year'] . "</td>";
													echo "<td>" . $row['file'] . "</td>";
													echo "<td>" . $row['members'] . "</td>";
													echo "</tr>";
													$row = $res->fetch_assoc();
												}
											}
										?>
								<hr class="star-primary">
							</div>
						</div>
						<div class="row">
							<div class="col-lg-8 col-lg-offset-2">
								<!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
								<!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
							</div>
						</div>
					</div>
				</section>
				<footer class="container" style="min-height:200px; background-color:#18bc9c;color:#fff;text-align:center;padding-top:50px;">
					INSPIRED BY PURECSS.IO © 2015 
				</footer>
			</div>







						<div class="container">
							<div class="header clearfix">
								
							</div>	

						</div> <!-- /container -->


						<script type="text/template" id="table_heading">
							<table class="table table-bordered">
								<thead>
								<tr>
									<th>Id</th><th>Projname</th><th>CourseCode</th><th>CourseName</th><th>Year</th><th>members</th>
								</tr>
								</thead>
								<tbody>
						</script>

						<table class="table table-bordered">
								<thead>
									<tr>
										<th>Project ID</th>
										<th>Project Name</th>
										<th>Course Code</th>
										<th>Course Name</th>
										<th>GitHub Link</th>
										<th>Year</th>
										<th>File</th>
										<th>Group Members</th>
									</tr>
								</thead>
								<tbody>
							<?php
								
								$conn = getDBConnection();
								$sql = "SELECT * FROM `project`";
								$res = $conn->query($sql);
								if ($res){
									$row = $res->fetch_assoc();
									while ($row != null){
										// print the rows of the table
										echo "<tr>";
										echo "<td>" . $row['id'] . "</td>";
										echo "<td>" . $row['projname'] . "</td>";
										echo "<td>" . $row['coursecode'] . "</td>";
										echo "<td>" . $row['coursename'] . "</td>";
										echo "<td>" . $row['githublink'] . "</td>";
										echo "<td>" . $row['year'] . "</td>";
										echo "<td>" . $row['file'] . "</td>";
										echo "<td>" . $row['members'] . "</td>";
										echo "</tr>";
										$row = $res->fetch_assoc();
									}
								}
							?>


</body>
</html>
