<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta="author" content="">
	
	<title>Student Project Tracker</title>
	
	<link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	
	
	<link href="css/ie10-viewport-bug-workaround.css" rel="stylesheet">
	
	
	<link href="css/jumbotron-narrow.css" rel="stylesheet">
	<link href="css/signin.css" rel="stylesheet">


<body>
		<nav class="navbar navbar-default navbar-fixed-top">
				<div class="container">

					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav navbar-right">
							<li class="hidden">
								<a href="#page-top"></a>
							</li>
							<li class="page-scroll">
								<a href="index.php/signin">Sign In</a>
							</li>
							<li class="page-scroll">
								<a href="index.php/signup">Sign Up</a>
							</li>
							<li class="page-scroll">
								<a href="#about">About</a>
							</li>
							<li class="page-scroll">
								<a href="#portfolio">Types of Projects</a>
							</li>
							
							<li class="page-scroll">
								<a href="#table">Current Projects</a>
							</li>
							
						</ul>
					</div>
				
				</div>
				
			</nav>

			<br>
			<br>
			<br>
			<br>
			<header>
				<div class="container" style="min-height:200px; background-color:#18bc9c;color:#fff;text-align:center;padding-top:50px;">
					<div class="row">
						<div>
							<div class="intro-text">
								<span class="name"><H1>Welcome to Student Project Tracker</h1></span>
								<p>Repository for Past and Present Student Porjects</p>

							</div>
						</div>
					</div>
				</div>
			</header>
			<br>
			<br>
			<br>
			<br>

			<div class="container" style="min-height:200px; background-color:#F5F5DC;color:#2F4F4Ftext-align:center;padding-top:50px;">
				<br>
			<br>
				<section class="primary" id="about">
					<div class="row">
						<span class="col-lg-3 col-lg-offset-1" ></span>
						<div>
							
							<span class="col-lg-3 col-lg-offset-1"><H1>About</h1></span>
							<div class="col-lg-4 col-lg-offset-2">
								<p>Student projet tracker is a web application that allows access to both present and past students of the university.It allows past students to upload their projects for viewing and downloading by current students. </p>
							</div>
							<div class="col-lg-4">
								<p>These current students can use these past projects to pick up where it was left off and use snippets of the projects in their projects once granted permission. For the innovative students they can use this to have an idea what projects were already attempted.</p>
							</div>
							</div>	
						</div>
					</div>

				</section>
			</div>
			<br>
			<br>
			<br>
			<br>
			<div class="content-wrapper">
				<section class="primary" id="portfolio">
					<div class="container">
						<div class="row">
							<div class="col-lg-12 text-center">
								<h2>Types of Projects</h2>
								<hr class="star-primary">
							</div>
						</div>
						<div class="row">
							<div class="col-sm-4">
								<img src="src/arts.jpg" width="200" height="150">    
							</div>
							<br>
							<br>
							<div class="col-sm-4">
								<img src="src/STEM.jpg" width="200" height="150">    
							</div>
							<br>
							<br>
							<div class="col-sm-4">
								<img src="src/SS.jpg" width="200" height="150">    
							</div>
						</div>
					</div>
				</section>
				<br>
				<br>
				<br>
				<br>
			
				<section class="primary" id="table">
					<div class="container">
						<div class="row">
							<div class="col-lg-12 text-center">
						
								<table class="table table-hover" style="background-color:#F5F5DC;">
											<thead>
												<tr>
													
													<th>Project Name</th>
													<th>Course Code</th>
													<th>Course Name</th>
													<th>Year</th>
													<th>Group Members</th>
												</tr>
											</thead>
											<tbody>
										<?php
											
											$conn = getDBConnection();
											$sql = "SELECT * FROM `project`";
											$res = $conn->query($sql);
											if ($res){
												$row = $res->fetch_assoc();
												while ($row != null){
													// print the rows of the table
													echo "<tr>";
													echo "<td>" . $row['projname'] . "</td>";
													echo "<td>" . $row['coursecode'] . "</td>";
													echo "<td>" . $row['coursename'] . "</td>";
													echo "<td>" . $row['year'] . "</td>";
													echo "<td>" . $row['members'] . "</td>";
													echo "</tr>";
													$row = $res->fetch_assoc();
												}
											}
										?>
								<hr class="star-primary">
							</div>
						</div>
						
					</div>
				</section>
				<footer class="container" style="min-height:200px; background-color:#18bc9c;color:#fff;text-align:center;padding-top:50px;">
					<h1>STEPS</h1>
					<p>Sign Up to create an account. You may login however you won't get full access until you get approved by and administrator. Restricted for full access users include the ability to download and upload projects</p>
					<br>
					<p>A product of Uwi faculty of Scienece and Techonolgy</p>
				</footer>
			</div>


</body>
</html>

