<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sign Up</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="../css/signin.css" rel="stylesheet">
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../js/ie10-viewport-bug-workaround.js"></script>
<script src="../bower_components/jquery/dist/jquery.js"></script>
<script src="../js/main.js"></script>
</head>

<body>
     <nav class="navbar navbar-default navbar-fixed-top">

				<div class="col-md-5 col-md-offset-5">					
					
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav navbar-right">
							<li class="hidden">
								<a href="#page-top"></a>
							</li>
							<li class="page-scroll">
								<a href="../index.php">Home</a>
							</li>
							<li class="page-scroll">
								<a href="../profile.php">Profile</a>
							</li>
							<li class="page-scroll">
								<a href="../signup.php">Sign Up</a>
							</li>
																										
						</ul>
					</div>
					
				</div>
    </nav>

    <div class="container">

        <form class="form-signin">
            <h2 class="form-signin-heading">Sign In</h2>
            <label for="username" class="sr-only">Username</label>
            <input type="text" id="username" class="form-control" placeholder="username" required autofocus>
            <label for="password" class="sr-only">Password</label>
            <input type="password" id="password" class="form-control" placeholder="Password" required autofocus>
            <input class="btn btn-lg btn-primary btn-block" type="button" id="signinBtn" value="SignIn">
            <a class="btn btn-lg btn-primary btn-block" href="forgot.phtml">Forgot password?</a>
        </form>

        <div id="resp"></div>
    </div> <!-- /container -->

</body>
</html>