<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Profile</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>

    <!-- Custom styles for this template -->
    <link href="../css/signin.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../js/ie10-viewport-bug-workaround.js"></script>
    <script src="../bower_components/jquery/dist/jquery.js"></script>
    
    </head>

<body>

<div class="container">

    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Profile</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="../css/signin.css" rel="stylesheet">
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../js/ie10-viewport-bug-workaround.js"></script>
<script src="../js/chart.js"></script>
<script src="../bower_components/jquery/dist/jquery.js"></script>

</head>

<body>

<div class="container">
    
    <div class="container">
        <div class="fb-profile">
            <img align="left" class="fb-image-lg" src="http://northbaynow.ca/wp-content/uploads/2016/05/tech.jpg" alt="Profile image example"/>
            <img align="left" class="fb-image-profile thumbnail" src="../src/propics/blank.jpg" alt="Profile image example" height="180" width="180"/>
            <div class="fb-profile-text">
                <h1>Eli Macy</h1>
                <p>Girls just wanna go fun.</p>
            </div>
        </div>
    </div> 
    <div>
        <br>
    </div>
    <ul class="nav nav-pills" role="tablist">
        <li role="presentation" class="active"><a href="../index.php">Home</a></li>
        <li role="presentation"><a href="../profile.php">Add your own Project</a></li>
        <li role="presentation"><a href="pendAcc.phtml">Pending Accounts<span class="badge">0</span></a></li>
        <li role="presentation"><a href="update.phtml">Update your Info</a></li>
        <li role="presentation"><a href="update.phtml">View and Download Projects</a></li>
    </ul>
    <div>
            <br>
            <br>
    </div>
    <div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
</div> <!-- /container -->

</body>
</html>

    <div id="resp"></div>
</div> <!-- /container -->

</body>
</html>