<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Profile</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="css/signin.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="js/main.js"></script>
    </head>

<body>

<div class="container">

    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Profile</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="css/signin.css" rel="stylesheet">
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="js/ie10-viewport-bug-workaround.js"></script>
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="js/main.js"></script>
</head>

<body>

<div class="container">

    <nav class="navbar navbar-inverse">
        <li><a class="navbar-brand" href="addproj.phtml">Add your own Project</a></li>
        <li><a href="popProj.phtml">Most Popular Projects</a></li>
        <li><a href="pendAcc.phtml">See Pending Accounts</a></li>
        <li><a href="update.phtml">Update your info</a></li>
    </nav>
   
</div> <!-- /container -->

</body>
</html>

    <div id="resp"></div>
</div> <!-- /container -->

</body>
</html>