<!DOCTYPE html>
<?php $num =0;
$_SESSION['fromSignin'] = $num++; ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Profile</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>


    <!-- Custom styles for this template -->
    <link href="../css/signin.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../js/ie10-viewport-bug-workaround.js"></script>
    <script src="../bower_components/jquery/dist/jquery.js"></script>
    <link href="../css/signin.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../js/ie10-viewport-bug-workaround.js"></script>
    <script src="../js/chart.js"></script>
    <script src="../bower_components/jquery/dist/jquery.js"></script>
    
    </head>

<body>

<div class="container">

   

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
 				<div class="col-md-5 col-md-offset-5">					
 					
 					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 						<ul class="nav navbar-nav navbar-right">
 							<li class="hidden">
 								<a href="#page-top"></a>
 							</li>
 							
                             <li class="page-scroll">
 								<a href="../profile.php/logout">Log Out</a>
 							</li>
 																										
 						</ul>
 					</div>
 					
 				</div>
    </nav>
    <br>
	<br>

<div class="container">
    
    <div class="container">
        <div class="fb-profile">
            <img align="left" class="fb-image-lg" src="http://northbaynow.ca/wp-content/uploads/2016/05/tech.jpg" alt="Profile image example"/>
            <img align="left" class="fb-image-profile thumbnail" src="../src/propics/blank.jpg" alt="Profile image example" height="180" width="180"/>
            <div class="fb-profile-text">
                <h1>Welcome</h1>
                <?php
                    echo "<h1>'".$_SESSION['userData']['username']."'</h1>";
                    echo "<h2>".$_SESSION['userData']['firstname']." ".$_SESSION['userData']['lastname']."</h2>";
                    



                ?>
                
            </div>
        </div>
    </div> 
    <div>
        <br>
    </div>
    <ul class="nav nav-pills" role="tablist">
        <?php
        	echo '<li role="presentation" class="active"><a href="../profile.php/home">Home</a></li>';
		
			if($_SESSION['userData']['approval'] == 'Yes'){
				echo '<li role="presentation"><a href="../profile.php/addproj">Add your own Project</a></li>';
			}
		
            if($_SESSION['userData']['accounttype'] == 'Admin'){
                echo '<li role="presentation"><a href="../profile.php/pending">Pending Accounts<span class="badge">';
                
                $count = 0;
                $count = countPending();
                echo $count;
                echo '</span></a></li>';
            }
        
        	echo '<li role="presentation"><a href="../profile.php/change">Update your Info</a></li>';
		
			if($_SESSION['userData']['approval'] == 'Yes'){

				echo '<li role="presentation"><a href="../profile.php/download">View and Download Projects</a></li>';
			}

		
        	echo '<li role="presentation"><a href="../profile.php/compare">Compare Code</a></li>';
		?>
    </ul>
    <div>
            <br>
            <br>
    </div>
    <div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
</div> <!-- /container -->

</body>
</html>

    <div id="resp"></div>
</div> <!-- /container -->

</body>
</html>