<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Profile</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script> 
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>


    <!-- Custom styles for this template -->
    <link href="css/signin.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>
    <!--<script src="bower_components/jquery/dist/jquery.js"></script> -->
    <link href="css/signin.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>
    <!-- <script src="bower_components/jquery/dist/jquery.js"></script> -->
    
    </head>

<body>

<div class="container">

   

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
 				<div class="col-md-5 col-md-offset-5">					
 					
 					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 						<ul class="nav navbar-nav navbar-right">
 							<li class="hidden">
 								<a href="#page-top"></a>
 							</li>
 							<li class="page-scroll">
 								<a href="index.php">Home</a>
 							</li>
 							<li class="page-scroll">
 								<a href="signup.php">Sign Up</a>
 							</li>
 							<li class="page-scroll">
 								<a href="templates/signin.phtml">Sign In</a>
 							</li>
 																										
 						</ul>
 					</div>
 					
 				</div>
    </nav>

    <div class="container">
        
        <div class="container">
            <div class="fb-profile">
                <img align="left" class="fb-image-lg" src="http://northbaynow.ca/wp-content/uploads/2016/05/tech.jpg" alt="Profile image example"/>
                <img align="left" class="fb-image-profile thumbnail" src="src/propics/blank.jpg" alt="Profile image example" height="180" width="180"/>
                <div class="fb-profile-text">
                    <h1>Eli Macy</h1>
                    <p>Girls just wanna go fun.</p>
                </div>
            </div>
        </div> 
        <div>
            <br>
        </div>
        <ul class="nav nav-pills" role="tablist">
            <li role="presentation"><a href="templates/stuProfile.phtml">Home</a></li>
            <li role="presentation"><a href="profile.php">Add your own Project</a></li>
            <li role="presentation"><a href="pending.php">Pending Accounts<span class="badge">0</span></a></li>
            <li role="presentation"><a href="templates/change.phtml">Update your Info</a></li>
            <li role="presentation" class="active"><a href="download.php">View and Download Projects</a></li>
            <li role="presentation"><a href="templates/compare.phtml">Compare Code</a></li>
        </ul>
        <div>
                <br>
                <br>
        </div>
        
    </div>
    <!--
    <div class="container-fluid">
		<div class="col-lg-20 col-md-offset-2 table-responsive">
			<h4>Projects</h4>
			<p>A table Showing all Projects Stored click to Download</p>
			<div id="table_sec"></div>
		</div>
	</div>
   
    <script type="text/template" id="table_heading">
	    <table class="table table-bordered">
		<thead>
		<tr>
			<th>ProjectId</th><th>Project Name</th><th>Course Code</th><th>Course Name</th><th>Git Link</th><th>year</th><th>file</th><th>members</th>
		</tr>
		</thead>
		<tbody>
    </script> -->
    <table class="table table-bordered">
											<thead>
												<tr>
													<th>Project ID</th>
													<th>Project Name</th>
													<th>Course Code</th>
													<th>Course Name</th>
													<th>GitHub Link</th>
													<th>Year</th>
													<th>Project File</th>
													<th>Group Members</th>
												</tr>
											</thead>
											<tbody>
    <?php
                                                
        $conn = getDBConnection();
        $sql = "SELECT * FROM `project`";
        $res = $conn->query($sql);
        if ($res){
            $row = $res->fetch_assoc();
            while ($row != null){
                // print the rows of the table
                echo "<tr>";
                echo "<td>" . $row['id'] . "</td>";
                echo "<td>" . $row['projname'] . "</td>";
                echo "<td>" . $row['coursecode'] . "</td>";
                echo "<td>" . $row['coursename'] . "</td>";
                echo "<td>" . $row['githublink'] . "</td>";
                echo "<td>" . $row['year'] . "</td>";
                echo "<td>" . $row['file'] . "</td>";
                echo "<td>" . $row['members'] . "</td>";
                echo "</tr>";
                $row = $res->fetch_assoc();
            }
        }
    ?>
    </table>
<script src="js/main.js"></script>
</body>
</html>

    <div id="resp"></div>
</div> <!-- /container -->

</body>
</html>