<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>View and Download</title>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script> 
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>


    <!-- Custom styles for this template -->
    <link href="../css/signin.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../js/ie10-viewport-bug-workaround.js"></script>
    <!--<script src="bower_components/jquery/dist/jquery.js"></script> -->
    <link href="../css/signin.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../js/ie10-viewport-bug-workaround.js"></script>
    <!-- <script src="bower_components/jquery/dist/jquery.js"></script> -->
    
    </head>

<body>

<div class="container">

   

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
 				<div class="col-md-5 col-md-offset-5">					
 					
 					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 						<ul class="nav navbar-nav navbar-right">
 							<li class="hidden">
 								<a href="#page-top"></a>
 							</li>
 							<li class="page-scroll">
 								<a href="../profile.php/logout">Log Out</a>
 							</li>		
 																										
 						</ul>
 					</div>
 					
 				</div>
    </nav>
    <br>
	<br>

    <div class="container">
        
        <div class="container">
            <div class="fb-profile">
                <img align="left" class="fb-image-lg" src="http://northbaynow.ca/wp-content/uploads/2016/05/tech.jpg" alt="Profile image example"/>
                <img align="left" class="fb-image-profile thumbnail" src="../src/propics/blank.jpg" alt="Profile image example" height="180" width="180"/>
                <div class="fb-profile-text">
                    
                </div>
            </div>
        </div> 
        <div>
            <br>
        </div>
        <ul class="nav nav-pills" role="tablist">
            <?php
        	echo '<li role="presentation"><a href="../profile.php/home">Home</a></li>';
		
			if($_SESSION['userData']['approval'] == 'Yes'){
				echo '<li role="presentation" class="active"><a href="../profile.php/addproj">Add your own Project</a></li>';
			}
		
            if($_SESSION['userData']['accounttype'] == 'Admin'){
                echo '<li role="presentation"><a href="../profile.php/pending">Pending Accounts<span class="badge">';
                
                $count = 0;
                $count = countPending();
                echo $count;
                echo '</span></a></li>';
            }
        
        	echo '<li role="presentation"><a href="../profile.php/change">Update your Info</a></li>';
		
			if($_SESSION['userData']['approval'] == 'Yes'){

				echo '<li role="presentation" class="active"><a href="../profile.php/download">View and Download Projects</a></li>';
			}

		
        	echo '<li role="presentation"><a href="../profile.php/compare">Compare Code</a></li>';
		?>
        </ul>
        <div>
                <br>
                <br>
        </div>
        
    </div>
   
    <table class="table table-bordered">
											<thead>
												<tr>
													<th>Project ID</th>
													<th>Project Name</th>
													<th>Course Code</th>
													<th>Course Name</th>
													<th>GitHub Link</th>
													<th>Year</th>
													<th>Project File</th>
													<th>Group Members</th>
												</tr>
											</thead>
											<tbody>
    <?php
                                                
        $conn = getDBConnection();
        $sql = "SELECT * FROM `project`";
        $res = $conn->query($sql);
        $link = "";
        if ($res){
            $row = $res->fetch_assoc();
            while ($row != null){
                // print the rows of the table
                echo "<tr>";
                echo "<td>" . $row['id'] . "</td>";
                echo "<td>" . $row['projname'] . "</td>";
                echo "<td>" . $row['coursecode'] . "</td>";
                echo "<td>" . $row['coursename'] . "</td>";
                $link = $row['githublink'];
                echo "<td>";
                echo '<a href="https://'.$link.'">View this Project on GitHub</a>';
                echo "</td>";
                echo "<td>" . $row['year'] . "</td>";
                $file = $row['file'];
                if($file != "" && $file != " "){
                    echo "<td>";
                    echo '<a href="../useruploads/'.$file.'">Download This project</a>';
                    echo "</td>";
                }
                else{
                    echo "<td>Not Available</td>";
                }    
                //echo "<td>" . $row['file'] . "</td>";
                echo "<td>" . $row['members'] . "</td>";
                echo "<td></td>";
                echo "</tr>";
                $row = $res->fetch_assoc();
            }
        }
    ?>
    </table>
<script src="js/main.js"></script>
</body>
</html>

    <div id="resp"></div>
</div> <!-- /container -->

</body>
</html>